# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Snowex Hackweek
author: eScience Institute, University of Washington
logo: logo.png

parse:
  myst_substitutions:
    hackweek: snowex-hackweek
    dates: July 12 to 16, 2021

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/snowex-hackweek/website
  path_to_book: book
  branch: main

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
